import * as core from '@actions/core'
import { readFile } from 'node:fs/promises'

const GITHUB_API_URL = 'https://api.github.com'
const MAX_SEARCH_PAGE_SIZE = 100
const MAX_SEARCH_RESULTS = 1000

const DEFAULTS = {
  'fail-on-threshold': 'false',
  'close-pr-on-threshold': 'false',
  'close-linked-author-issues': 'true',
  'fail-threshold': '100',
  'one-day-window-hours': '24',
  'one-day-pr-threshold': '20',
  'seven-day-window-days': '7',
  'seven-day-pr-threshold': '100',
  'sample-size': '100',
  'cross-repo-threshold': '30',
  'template-markers': 'Made with [Cursor]\nGenerated with\nGenerated by',
  'template-marker-ratio-threshold': '0.3',
  'trusted-author-associations': 'OWNER,MEMBER,COLLABORATOR,CONTRIBUTOR',
  'prior-merged-pr-threshold': '1',
  'weight-one-day-prs': '40',
  'weight-seven-day-prs': '40',
  'weight-cross-repo': '30',
  'weight-template-markers': '15',
  'weight-untrusted-association': '10',
  'weight-no-prior-merged': '20'
}

function input(name) {
  const value = core.getInput(name)
  return value === '' ? DEFAULTS[name] || '' : value
}

function numberInput(name, { min = 0, max = Number.MAX_SAFE_INTEGER } = {}) {
  const value = Number(input(name))

  if (!Number.isFinite(value) || value < min || value > max) {
    throw new Error(
      `Input "${name}" must be a number between ${min} and ${max}`
    )
  }

  return value
}

function booleanInput(name) {
  return ['1', 'true', 'yes', 'on'].includes(input(name).toLowerCase())
}

function listInput(name) {
  return input(name)
    .split(/[\n,]/)
    .map((item) => item.trim())
    .filter(Boolean)
}

function sinceISOString(now, milliseconds) {
  return new Date(now.getTime() - milliseconds).toISOString()
}

function parseRepositoryName(event) {
  return (
    event.repository?.full_name ||
    (event.repository?.owner?.login && event.repository?.name
      ? `${event.repository.owner.login}/${event.repository.name}`
      : '')
  )
}

function getPullRequestContext(event) {
  const pullRequest = event.pull_request

  if (!pullRequest?.user?.login) {
    return null
  }

  return {
    author: pullRequest.user.login,
    association: pullRequest.author_association || 'NONE',
    body: pullRequest.body || '',
    number: pullRequest.number || event.number,
    repository: parseRepositoryName(event)
  }
}

async function readEvent(env) {
  if (!env.GITHUB_EVENT_PATH) {
    return {}
  }

  return JSON.parse(await readFile(env.GITHUB_EVENT_PATH, 'utf8'))
}

async function githubSearch(fetchImpl, token, query, pageSize = 1, page = 1) {
  const url = new URL('/search/issues', GITHUB_API_URL)
  url.searchParams.set('q', query)
  url.searchParams.set('per_page', String(pageSize))
  url.searchParams.set('page', String(page))

  const headers = {
    accept: 'application/vnd.github+json',
    'user-agent': 'anti-slop-action'
  }

  if (token) {
    headers.authorization = `Bearer ${token}`
  }

  const response = await fetchImpl(url, { headers })

  if (!response.ok) {
    const body = await response.text().catch(() => '')
    throw new Error(
      `GitHub Search API failed for "${query}" with ${response.status}: ${body}`
    )
  }

  return response.json()
}

async function closePullRequest(fetchImpl, token, repository, pullNumber) {
  if (!token) {
    throw new Error('Input "github-token" is required to close pull requests')
  }

  if (!repository || !pullNumber) {
    throw new Error(
      'Pull request repository and number are required to close it'
    )
  }

  const url = new URL(
    `/repos/${repository}/pulls/${pullNumber}`,
    GITHUB_API_URL
  )
  const response = await fetchImpl(url, {
    method: 'PATCH',
    headers: {
      accept: 'application/vnd.github+json',
      authorization: `Bearer ${token}`,
      'content-type': 'application/json',
      'user-agent': 'anti-slop-action'
    },
    body: JSON.stringify({ state: 'closed' })
  })

  if (!response.ok) {
    const body = await response.text().catch(() => '')
    throw new Error(
      `Failed to close pull request ${repository}#${pullNumber} with ${response.status}: ${body}`
    )
  }
}

function githubHeaders(token, extraHeaders = {}) {
  const headers = {
    accept: 'application/vnd.github+json',
    'user-agent': 'anti-slop-action',
    ...extraHeaders
  }

  if (token) {
    headers.authorization = `Bearer ${token}`
  }

  return headers
}

function parseClosingIssueReferences(body, defaultRepository) {
  const references = new Map()
  const keywordPattern =
    /\b(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+((?:(?:[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+)?#\d+)(?:[\s,]*(?:and\s+)?(?:(?:[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+)?#\d+))*)/gi
  const referencePattern =
    /(?:(?<repository>[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+))?#(?<number>\d+)/g

  for (const keywordMatch of body.matchAll(keywordPattern)) {
    for (const referenceMatch of keywordMatch[1].matchAll(referencePattern)) {
      const repository =
        referenceMatch.groups.repository || defaultRepository || ''
      const number = Number(referenceMatch.groups.number)

      if (!repository || !number) continue

      references.set(`${repository}#${number}`, { repository, number })
    }
  }

  return [...references.values()]
}

async function readIssue(fetchImpl, token, repository, number) {
  const url = new URL(`/repos/${repository}/issues/${number}`, GITHUB_API_URL)
  const response = await fetchImpl(url, {
    headers: githubHeaders(token)
  })

  if (!response.ok) {
    const body = await response.text().catch(() => '')
    throw new Error(
      `Failed to read issue ${repository}#${number} with ${response.status}: ${body}`
    )
  }

  return response.json()
}

async function closeIssue(fetchImpl, token, repository, number) {
  const url = new URL(`/repos/${repository}/issues/${number}`, GITHUB_API_URL)
  const response = await fetchImpl(url, {
    method: 'PATCH',
    headers: githubHeaders(token, { 'content-type': 'application/json' }),
    body: JSON.stringify({ state: 'closed' })
  })

  if (!response.ok) {
    const body = await response.text().catch(() => '')
    throw new Error(
      `Failed to close issue ${repository}#${number} with ${response.status}: ${body}`
    )
  }
}

async function closeLinkedAuthorIssues({
  fetchImpl,
  token,
  repository,
  body,
  author
}) {
  const references = parseClosingIssueReferences(body, repository)
  const closed = []

  for (const reference of references) {
    try {
      const issue = await readIssue(
        fetchImpl,
        token,
        reference.repository,
        reference.number
      )

      if (issue.pull_request || issue.state === 'closed') {
        continue
      }

      if (issue.user?.login !== author) {
        core.info(
          `Skipping linked issue ${reference.repository}#${reference.number}; author is ${issue.user?.login || 'unknown'}`
        )
        continue
      }

      await closeIssue(fetchImpl, token, reference.repository, reference.number)
      closed.push(`${reference.repository}#${reference.number}`)
    } catch (error) {
      if (error instanceof Error) {
        core.warning(error.message)
      }
    }
  }

  return closed
}

async function countSearch(fetchImpl, token, query) {
  const result = await githubSearch(fetchImpl, token, query, 1)
  return result.total_count || 0
}

async function sampleSearch(fetchImpl, token, query, sampleSize) {
  const cappedSampleSize = Math.min(sampleSize, MAX_SEARCH_RESULTS)
  const pageCount = Math.ceil(cappedSampleSize / MAX_SEARCH_PAGE_SIZE)
  const items = []

  for (let page = 1; page <= pageCount; page += 1) {
    const remaining = cappedSampleSize - items.length
    const pageSize = Math.min(MAX_SEARCH_PAGE_SIZE, remaining)
    const result = await githubSearch(fetchImpl, token, query, pageSize, page)
    items.push(...(result.items || []))

    if (!result.items?.length || items.length >= result.total_count) {
      break
    }
  }

  return items.slice(0, cappedSampleSize)
}

function repositoryFromIssue(item) {
  return item.repository_url?.split('/').slice(-2).join('/') || ''
}

function hasTemplateMarker(item, markers) {
  const body = (item.body || '').toLowerCase()
  return markers.some((marker) => body.includes(marker.toLowerCase()))
}

function buildConfig() {
  return {
    token: input('github-token') || process.env.GITHUB_TOKEN || '',
    failOnThreshold: booleanInput('fail-on-threshold'),
    closePrOnThreshold: booleanInput('close-pr-on-threshold'),
    closeLinkedAuthorIssues: booleanInput('close-linked-author-issues'),
    failThreshold: numberInput('fail-threshold', { min: 1 }),
    oneDayWindowHours: numberInput('one-day-window-hours', { min: 1 }),
    oneDayPrThreshold: numberInput('one-day-pr-threshold'),
    sevenDayWindowDays: numberInput('seven-day-window-days', { min: 1 }),
    sevenDayPrThreshold: numberInput('seven-day-pr-threshold'),
    sampleSize: numberInput('sample-size', { min: 1, max: MAX_SEARCH_RESULTS }),
    crossRepoThreshold: numberInput('cross-repo-threshold'),
    templateMarkers: listInput('template-markers'),
    templateMarkerRatioThreshold: numberInput(
      'template-marker-ratio-threshold',
      { min: 0, max: 1 }
    ),
    trustedAuthorAssociations: listInput('trusted-author-associations').map(
      (association) => association.toUpperCase()
    ),
    priorMergedPrThreshold: numberInput('prior-merged-pr-threshold'),
    weights: {
      oneDayPrs: numberInput('weight-one-day-prs'),
      sevenDayPrs: numberInput('weight-seven-day-prs'),
      crossRepo: numberInput('weight-cross-repo'),
      templateMarkers: numberInput('weight-template-markers'),
      untrustedAssociation: numberInput('weight-untrusted-association'),
      noPriorMerged: numberInput('weight-no-prior-merged')
    }
  }
}

function scoreRules(metrics, config) {
  const triggeredRules = []

  function addRule(name, weight, details) {
    if (weight <= 0) return
    triggeredRules.push({ name, weight, details })
  }

  if (metrics.oneDayPrCount > config.oneDayPrThreshold) {
    addRule(
      'one_day_pr_volume',
      config.weights.oneDayPrs,
      `${metrics.oneDayPrCount} PRs in ${config.oneDayWindowHours}h`
    )
  }

  if (metrics.sevenDayPrCount > config.sevenDayPrThreshold) {
    addRule(
      'seven_day_pr_volume',
      config.weights.sevenDayPrs,
      `${metrics.sevenDayPrCount} PRs in ${config.sevenDayWindowDays}d`
    )
  }

  if (metrics.uniqueRepoCount > config.crossRepoThreshold) {
    addRule(
      'cross_repo_volume',
      config.weights.crossRepo,
      `${metrics.uniqueRepoCount} repositories in sample`
    )
  }

  if (
    metrics.templateMarkerRatio >= config.templateMarkerRatioThreshold &&
    metrics.templateMarkerCount > 0
  ) {
    addRule(
      'template_marker_ratio',
      config.weights.templateMarkers,
      `${metrics.templateMarkerCount}/${metrics.sampleSize} sampled PRs matched configured markers`
    )
  }

  if (!config.trustedAuthorAssociations.includes(metrics.authorAssociation)) {
    addRule(
      'untrusted_author_association',
      config.weights.untrustedAssociation,
      `author_association is ${metrics.authorAssociation}`
    )
  }

  if (metrics.priorMergedPrCount < config.priorMergedPrThreshold) {
    addRule(
      'no_prior_merged_prs',
      config.weights.noPriorMerged,
      `${metrics.priorMergedPrCount} merged PRs in this repository`
    )
  }

  const score = triggeredRules.reduce((total, rule) => total + rule.weight, 0)

  return {
    score,
    riskLevel:
      score >= config.failThreshold
        ? 'high'
        : score >= config.failThreshold / 2
          ? 'medium'
          : 'low',
    triggeredRules
  }
}

function setResultOutputs(metrics, result) {
  core.setOutput('score', String(result.score))
  core.setOutput('risk-level', result.riskLevel)
  core.setOutput(
    'triggered-rules',
    result.triggeredRules.map((rule) => rule.name).join(',')
  )
  core.setOutput('details', JSON.stringify({ metrics, ...result }))
  core.setOutput('one-day-pr-count', String(metrics.oneDayPrCount))
  core.setOutput('seven-day-pr-count', String(metrics.sevenDayPrCount))
  core.setOutput('unique-repo-count', String(metrics.uniqueRepoCount))
  core.setOutput('template-marker-count', String(metrics.templateMarkerCount))
  core.setOutput('prior-merged-pr-count', String(metrics.priorMergedPrCount))
  core.setOutput('author-association', metrics.authorAssociation)
}

async function evaluatePullRequest({ event, fetchImpl, now }) {
  const config = buildConfig()
  const context = getPullRequestContext(event)

  if (!context) {
    return {
      skipped: true,
      message: 'No pull_request payload found; anti-slop only evaluates PRs.'
    }
  }

  const oneDaySince = sinceISOString(
    now,
    config.oneDayWindowHours * 60 * 60 * 1000
  )
  const sevenDaySince = sinceISOString(
    now,
    config.sevenDayWindowDays * 24 * 60 * 60 * 1000
  )
  const baseQuery = `author:${context.author} type:pr`
  const oneDayQuery = `${baseQuery} created:>=${oneDaySince}`
  const sevenDayQuery = `${baseQuery} created:>=${sevenDaySince}`
  const priorMergedQuery = `repo:${context.repository} author:${context.author} type:pr is:merged`

  const [oneDayPrCount, sevenDayPrCount, sampledItems, priorMergedPrCount] =
    await Promise.all([
      countSearch(fetchImpl, config.token, oneDayQuery),
      countSearch(fetchImpl, config.token, sevenDayQuery),
      sampleSearch(fetchImpl, config.token, sevenDayQuery, config.sampleSize),
      context.repository
        ? countSearch(fetchImpl, config.token, priorMergedQuery)
        : Promise.resolve(0)
    ])

  const uniqueRepoCount = new Set(
    sampledItems.map(repositoryFromIssue).filter(Boolean)
  ).size
  const templateMarkerCount = sampledItems.filter((item) =>
    hasTemplateMarker(item, config.templateMarkers)
  ).length
  const sampleSize = sampledItems.length

  const metrics = {
    author: context.author,
    authorAssociation: context.association.toUpperCase(),
    pullNumber: context.number,
    repository: context.repository,
    oneDayPrCount,
    sevenDayPrCount,
    sampleSize,
    uniqueRepoCount,
    templateMarkerCount,
    templateMarkerRatio:
      sampleSize === 0 ? 0 : templateMarkerCount / sampleSize,
    priorMergedPrCount
  }
  const result = scoreRules(metrics, config)

  return {
    config,
    metrics,
    pullRequestBody: context.body,
    result,
    skipped: false
  }
}

/**
 * The main function for the action.
 *
 * @param {object} options Test-only dependency overrides.
 * @returns {Promise<void>} Resolves when the action is complete.
 */
export async function run(options = {}) {
  try {
    const env = options.env || process.env
    const event = options.event || (await readEvent(env))
    const fetchImpl = options.fetchImpl || globalThis.fetch
    const now = options.now || new Date()

    if (!fetchImpl) {
      throw new Error('No fetch implementation is available')
    }

    const evaluation = await evaluatePullRequest({ event, fetchImpl, now })

    if (evaluation.skipped) {
      core.info(evaluation.message)
      core.setOutput('skipped', 'true')
      core.setOutput('score', '0')
      core.setOutput('risk-level', 'skipped')
      core.setOutput('pr-closed', 'false')
      core.setOutput('linked-issues-closed', '0')
      core.setOutput('linked-issue-refs', '')
      return
    }

    const { config, metrics, pullRequestBody, result } = evaluation
    setResultOutputs(metrics, result)
    core.setOutput('pr-closed', 'false')
    core.setOutput('linked-issues-closed', '0')
    core.setOutput('linked-issue-refs', '')
    core.info(
      `Anti-slop score for ${metrics.author}: ${result.score} (${result.riskLevel})`
    )

    for (const rule of result.triggeredRules) {
      core.info(`Triggered ${rule.name} (+${rule.weight}): ${rule.details}`)
    }

    if (config.closePrOnThreshold && result.score >= config.failThreshold) {
      await closePullRequest(
        fetchImpl,
        config.token,
        metrics.repository,
        metrics.pullNumber
      )
      core.setOutput('pr-closed', 'true')
      core.info(
        `Closed pull request ${metrics.repository}#${metrics.pullNumber} because score ${result.score} meets threshold ${config.failThreshold}`
      )

      if (config.closeLinkedAuthorIssues) {
        const closedIssues = await closeLinkedAuthorIssues({
          fetchImpl,
          token: config.token,
          repository: metrics.repository,
          body: pullRequestBody,
          author: metrics.author
        })

        core.setOutput('linked-issues-closed', String(closedIssues.length))
        core.setOutput('linked-issue-refs', closedIssues.join(','))
      }
    }

    if (config.failOnThreshold && result.score >= config.failThreshold) {
      core.setFailed(
        `Anti-slop score ${result.score} meets threshold ${config.failThreshold}`
      )
    }
  } catch (error) {
    if (error instanceof Error) core.setFailed(error.message)
  }
}

export const internals = {
  buildConfig,
  closeLinkedAuthorIssues,
  closePullRequest,
  evaluatePullRequest,
  parseClosingIssueReferences,
  scoreRules
}
