import { jest } from '@jest/globals'
import * as core from '../__fixtures__/core.js'

jest.unstable_mockModule('@actions/core', () => core)

const { run } = await import('../src/main.js')

function response(body) {
  return {
    ok: true,
    status: 200,
    json: async () => body
  }
}

function inputMap(overrides = {}) {
  const values = {
    'github-token': 'test-token',
    'fail-on-threshold': 'true',
    'close-pr-on-threshold': 'false',
    'close-linked-author-issues': 'true',
    'fail-threshold': '100',
    'one-day-window-hours': '24',
    'one-day-pr-threshold': '20',
    'seven-day-window-days': '7',
    'seven-day-pr-threshold': '100',
    'sample-size': '100',
    'cross-repo-threshold': '30',
    'template-markers': 'Made with [Cursor]\nGenerated with\nGenerated by',
    'template-marker-ratio-threshold': '0.3',
    'trusted-author-associations': 'OWNER,MEMBER,COLLABORATOR,CONTRIBUTOR',
    'prior-merged-pr-threshold': '1',
    'weight-one-day-prs': '40',
    'weight-seven-day-prs': '40',
    'weight-cross-repo': '30',
    'weight-template-markers': '15',
    'weight-untrusted-association': '10',
    'weight-no-prior-merged': '20',
    ...overrides
  }

  core.getInput.mockImplementation((name) => values[name] || '')
}

function searchMock() {
  return jest.fn(async (url) => {
    const parsed = new URL(url)
    const query = parsed.searchParams.get('q')

    if (query.includes('is:merged')) {
      return response({ total_count: 0, items: [] })
    }

    if (parsed.searchParams.get('per_page') === '1') {
      if (query.includes('created:>=2026-05-17T07:00:00.000Z')) {
        return response({ total_count: 30, items: [] })
      }

      if (query.includes('created:>=2026-05-11T07:00:00.000Z')) {
        return response({ total_count: 1067, items: [] })
      }
    }

    return response({
      total_count: 100,
      items: Array.from({ length: 100 }, (_, index) => ({
        body: index < 60 ? 'Made with [Cursor](https://cursor.com)' : '',
        repository_url: `https://api.github.com/repos/example/repo-${index}`
      }))
    })
  })
}

function closeCapableSearchMock(issueResponses = {}) {
  const requests = []
  const baseSearchMock = searchMock()
  const fetchImpl = jest.fn(async (url, options = {}) => {
    const parsed = new URL(url)
    requests.push({ url: String(url), options })

    if (options.method === 'PATCH') {
      return response({ state: 'closed' })
    }

    const issueMatch = parsed.pathname.match(
      /^\/repos\/(?<owner>[^/]+)\/(?<repo>[^/]+)\/issues\/(?<number>\d+)$/
    )

    if (issueMatch) {
      const repository = `${issueMatch.groups.owner}/${issueMatch.groups.repo}`
      const key = `${repository}#${issueMatch.groups.number}`
      return response(issueResponses[key])
    }

    return baseSearchMock(url, options)
  })

  fetchImpl.requests = requests
  return fetchImpl
}

describe('main.js', () => {
  beforeEach(() => {
    inputMap()
  })

  afterEach(() => {
    jest.resetAllMocks()
  })

  it('scores high-volume template-like PR authors', async () => {
    await run({
      now: new Date('2026-05-18T07:00:00.000Z'),
      fetchImpl: searchMock(),
      event: {
        repository: { full_name: 'Tlaster/anti-slop' },
        pull_request: {
          author_association: 'NONE',
          number: 123,
          user: { login: 'leno23' }
        }
      }
    })

    expect(core.setOutput).toHaveBeenCalledWith('score', '155')
    expect(core.setOutput).toHaveBeenCalledWith('risk-level', 'high')
    expect(core.setOutput).toHaveBeenCalledWith(
      'triggered-rules',
      'one_day_pr_volume,seven_day_pr_volume,cross_repo_volume,template_marker_ratio,untrusted_author_association,no_prior_merged_prs'
    )
    expect(core.setFailed).toHaveBeenCalledWith(
      'Anti-slop score 155 meets threshold 100'
    )
    expect(core.setOutput).toHaveBeenCalledWith('pr-closed', 'false')
  })

  it('closes the PR when configured and the score meets the threshold', async () => {
    inputMap({ 'close-pr-on-threshold': 'true' })
    const fetchImpl = closeCapableSearchMock()

    await run({
      now: new Date('2026-05-18T07:00:00.000Z'),
      fetchImpl,
      event: {
        repository: { full_name: 'Tlaster/anti-slop' },
        pull_request: {
          author_association: 'NONE',
          number: 123,
          user: { login: 'leno23' }
        }
      }
    })

    const closeRequest = fetchImpl.requests.find(
      (request) => request.options.method === 'PATCH'
    )

    expect(closeRequest.url).toBe(
      'https://api.github.com/repos/Tlaster/anti-slop/pulls/123'
    )
    expect(closeRequest.options.body).toBe(JSON.stringify({ state: 'closed' }))
    expect(core.setOutput).toHaveBeenCalledWith('pr-closed', 'true')
  })

  it('closes linked issues opened by the same author when closing the PR', async () => {
    inputMap({ 'close-pr-on-threshold': 'true' })
    const fetchImpl = closeCapableSearchMock({
      'Tlaster/anti-slop#321': {
        number: 321,
        state: 'open',
        user: { login: 'leno23' }
      },
      'Tlaster/anti-slop#654': {
        number: 654,
        state: 'open',
        user: { login: 'someone-else' }
      }
    })

    await run({
      now: new Date('2026-05-18T07:00:00.000Z'),
      fetchImpl,
      event: {
        repository: { full_name: 'Tlaster/anti-slop' },
        pull_request: {
          author_association: 'NONE',
          body: 'Closes #321 and fixes #654',
          number: 123,
          user: { login: 'leno23' }
        }
      }
    })

    const issuePatchUrls = fetchImpl.requests
      .filter(
        (request) =>
          request.options.method === 'PATCH' && request.url.includes('/issues/')
      )
      .map((request) => request.url)

    expect(issuePatchUrls).toEqual([
      'https://api.github.com/repos/Tlaster/anti-slop/issues/321'
    ])
    expect(core.setOutput).toHaveBeenCalledWith('linked-issues-closed', '1')
    expect(core.setOutput).toHaveBeenCalledWith(
      'linked-issue-refs',
      'Tlaster/anti-slop#321'
    )
  })

  it('skips non-PR events', async () => {
    await run({
      fetchImpl: searchMock(),
      event: { repository: { full_name: 'Tlaster/anti-slop' } }
    })

    expect(core.setOutput).toHaveBeenCalledWith('skipped', 'true')
    expect(core.setOutput).toHaveBeenCalledWith('risk-level', 'skipped')
    expect(core.setFailed).not.toHaveBeenCalled()
  })
})
